baseurl: "/"
url: "https://cuellar.fr"
permalink: pretty
title: Carlos Cuéllar
tagline: 'cuellar.fr'
description: "Carlos Cuéllar's personal site about design, technology and music."
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

logo:
  logo_desktop_image: /assets/images/logo/logo.svg
  logo_desktop_text: "cuellar.<strong>fr</strong>"
  logo_mobile_image: /assets/images/logo/logo.svg
  logo_mobile_text: ""
  logo_desktop_height: "36px"
  logo_desktop_width: "36px"
  logo_mobile_height: "36px"
  logo_mobile_width: "36px"

seo:
  meta_twitter_site: "@cuellarfr"
  meta_twitter_creator: "@cuellarfr"
  meta_og_image: "/assets/images/author/carlos2.webp"

# Config for post's excerpts
excerpt_separator: <!--more-->

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 10
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
    permalink: /blog/:path/
  cases:
    output: true
    permalink: /work/:path/
  shows:
    output: true
    permalink: /music/shows/:path/
  updates:
    output: true
    permalink: /now/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "work"
    values:
      sitemap: false
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "admin"
    values:
      sitemap: false

# GitHub info
github:
  repo: cuellarfr/cuellar.fr
  branch: master

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml

# PostCSS Cache
postcss:
  cache: false
